AccessManagementLaredo_App/Controllers/NewRequestController.cs
using AccessManagementLaredo;
using AccessManagementLaredo.HelperModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.Identity;
using System.Text.Json;
using AccessManagementLaredo_App.Models;
using System.Security.Claims;
using AccessManagementLaredo_App.Services;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http.Headers;
using AccessManagementLaredo.ViewModels;

namespace AccessManagementLaredo_App.Controllers
{
    public class NewRequestController : Controller
    {
        // variables ****************************************************************************
        //private IPermitRequestResidentialRepository _permitRequestResidentialRepository;
        private IPermitRequestRepository _permitRequestRepository;
        private ICountyRepository _countyRepository;
        private IHighwayRepository _highwayRepository;
        private IConstructionTypeRepository _constructionTypeRepository;
        private IPermitEventRepository _permitEventRepository;
        private IAttachmentTypeRepository _attachmentTypeRepository;
        private UserManager<ApplicationUser> _userManager;
        private IdentityServices _identityServices;
        private PermitEventHelperModel _permitEventHelperModel;
		private PermitRequestStatusHelperModel _permitRequestStatusHelperModel;
		private ExportPDF _exportPdf;
        private IWebHostEnvironment _webHostEnvironment;
		private IAttachmentRepository _attachmentRepository;
		private AttachmentHelperModel _attachmentHelperModel;

        // Controller ********************************************************************************************************************************************************************
        public NewRequestController(IPermitRequestRepository permitRequestRepository,ICountyRepository countyRepository , IHighwayRepository highwayRepository, 
            IConstructionTypeRepository constructionTypeRepository, IPermitEventRepository permitEventRepository, IAttachmentTypeRepository attachmentTypeRepository,
            UserManager<ApplicationUser> userManager, IdentityServices identityServices, PermitEventHelperModel permitEventHelperModel, 
			PermitRequestStatusHelperModel permitRequestStatusHelperModel, ExportPDF exportPDF, IWebHostEnvironment webHostEnvironment, IAttachmentRepository attachmentRepository)
        {
            _permitRequestRepository = permitRequestRepository;
			_countyRepository = countyRepository;
            _highwayRepository = highwayRepository;
            _constructionTypeRepository = constructionTypeRepository;
            _permitEventRepository = permitEventRepository;
            _attachmentTypeRepository = attachmentTypeRepository;
            _userManager = userManager;
            _identityServices = identityServices;
            _permitEventHelperModel = permitEventHelperModel;
			_permitRequestStatusHelperModel = permitRequestStatusHelperModel;
			_exportPdf = exportPDF;
			_webHostEnvironment = webHostEnvironment;
			_attachmentRepository = attachmentRepository;
        }

		// Index ********************************************************************************************************************************************************************
		public IActionResult Index()
        {
			ViewData["counties"] = GetCounties();
            ViewData["highways"] = GetHighways();
            ViewData["constructionTypes"] = GetConstructionTypes();
			ViewData["attachmentTypes"] = GetAttachmentTypes();
			ViewData["prefixesByCounty"] = GetPrefixesByCounty();

            return View();
        }

        // View to review permit requests ********************************************************************************************************************************************
        public IActionResult PermitRequestReview() 
		{ 
			return View();
		}


		// Action that creates a residential request ********************************************************************************************************************************
		[HttpPost]
        public IActionResult CreateResidential([DataSourceRequest] DataSourceRequest request, [FromBody] PermitRequestResidentialHelperModel permitRequestResidentialHelperModel)
        {
            var user = _identityServices.GetCurrentUserByName();
            //int sequenceValue = _permitRequestResidentialRepository.Create(permitRequestResidentialHelperModel);
            int sequenceValue = _permitRequestRepository.CreateResidential(permitRequestResidentialHelperModel);

            // An event is created every time a new residential request is created
            // First: Set values for event helper model
            _permitEventHelperModel.DateCreated = DateTime.Now;
			_permitEventHelperModel.PermitRequestId = sequenceValue;
            _permitEventHelperModel.PermitEventTypeCode = "RQST_STRT";
            _permitEventHelperModel.UserName = user.Result.ContactFullName;
            _permitEventHelperModel.UserRoleName = user.Result.ContactRole;
            _permitEventHelperModel.PermitEventComment = "";

			// Second: Create event
            _permitEventRepository.Create(_permitEventHelperModel);

			// Third: Update status
			//UpdateStatus(sequenceValue);

            permitRequestResidentialHelperModel.PermitRequestId = sequenceValue;
            _permitRequestRepository.DisposeDBObjects();
            return Json(new[] { permitRequestResidentialHelperModel }.ToDataSourceResult(request, ModelState));
        }

        // Action that creates a residential request ********************************************************************************************************************************
        [HttpPost]
        public IActionResult CreateCommercial([DataSourceRequest] DataSourceRequest request, [FromBody] PermitRequestCommercialHelperModel permitRequestCommercialHelperModel)
        {
            var user = _identityServices.GetCurrentUserByName();
            //int sequenceValue = _permitRequestResidentialRepository.Create(permitRequestResidentialHelperModel);
            int sequenceValue = _permitRequestRepository.CreateCommercial(permitRequestCommercialHelperModel);

            // An event is created every time a new residential request is created
            // First: Set values for event helper model
            _permitEventHelperModel.DateCreated = DateTime.Now;
            _permitEventHelperModel.PermitRequestId = sequenceValue;
            _permitEventHelperModel.PermitEventTypeCode = "RQST_STRT";
            _permitEventHelperModel.UserName = user.Result.ContactFullName;
            _permitEventHelperModel.UserRoleName = user.Result.ContactRole;
            _permitEventHelperModel.PermitEventComment = "";

            // Second: Create event
            _permitEventRepository.Create(_permitEventHelperModel);

            // Third: Update status
            //UpdateStatus(sequenceValue);

            permitRequestCommercialHelperModel.PermitRequestId = sequenceValue;
            _permitRequestRepository.DisposeDBObjects();
            return Json(new[] { permitRequestCommercialHelperModel }.ToDataSourceResult(request, ModelState));
        }

        // Action that updates an existing residential request **********************************************************************************************************************************
        [HttpPost]
		public IActionResult UpdateResidential([DataSourceRequest] DataSourceRequest request, [FromBody] PermitRequestResidentialHelperModel permitRequestResidentialHelperModel)
		{
            //_permitRequestRepository.Update(permitRequestResidentialHelperModel, (int)permitRequestResidentialHelperModel.PermitRequestId);
            _permitRequestRepository.UpdateResidential(permitRequestResidentialHelperModel, (int)permitRequestResidentialHelperModel.PermitRequestId);
            _permitRequestRepository.DisposeDBObjects();
			return Json(new[] { permitRequestResidentialHelperModel }.ToDataSourceResult(request, ModelState));
		}

        // Action that updates an existing commercial request **********************************************************************************************************************************
        [HttpPost]
        public IActionResult UpdateCommercial([DataSourceRequest] DataSourceRequest request, [FromBody] PermitRequestCommercialHelperModel permitRequestCommercialHelperModel)
        {
            //_permitRequestRepository.Update(permitRequestResidentialHelperModel, (int)permitRequestResidentialHelperModel.PermitRequestId);
            _permitRequestRepository.UpdateCommercial(permitRequestCommercialHelperModel, (int)permitRequestCommercialHelperModel.PermitRequestId);
            _permitRequestRepository.DisposeDBObjects();
            return Json(new[] { permitRequestCommercialHelperModel }.ToDataSourceResult(request, ModelState));
        }

        // Action that updates the internal revision section of a permit request ******************************************************************************************************
        [HttpPost]
        public void UpdateInternalReview([FromBody] PermitRequestInternalReviewHelperModel permitRequestInternalReviewHelperModel)
        {
            var user = _identityServices.GetCurrentUserByName();
            _permitRequestRepository.UpdateInternalSection(permitRequestInternalReviewHelperModel, (int)permitRequestInternalReviewHelperModel.PermitRequestId);

            // An event is created every time an internal user reviews (approve/reject) a permit request
            // If reviewAction is "pdf", no event is created and no status is updated.
			if (permitRequestInternalReviewHelperModel.ReviewAction == "form1058" || permitRequestInternalReviewHelperModel.ReviewAction == "finalPackage")
			{
				_permitRequestRepository.DisposeDBObjects();
				return;
			}

AccessManagementLaredo_App/Controllers/PermitRequestController.cs
using AccessManagementLaredo;
using AccessManagementLaredo.ViewModels;
using AccessManagementLaredo_App.Models;
using AccessManagementLaredo_App.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace AccessManagementLaredo_App.Controllers
{
    public class PermitRequestController : Controller
    {
        private IPermitRequestRepository _permitRequestRepository;
        private UserManager<ApplicationUser> _userManager;
        private IdentityServices _identityServices;

        // Constructor
        public PermitRequestController(IPermitRequestRepository permitRequestRepository, UserManager<ApplicationUser> userManager,
                IdentityServices identityServices)
        { 
            _permitRequestRepository = permitRequestRepository;
            _userManager = userManager;
            _identityServices = identityServices;
        }

        // Index action method
        public IActionResult Index()
        {
            return View();
        }

        //Read action method to fetch permit requests
        //public IActionResult Read([DataSourceRequest] DataSourceRequest request)
        //{
        //    string result = _permitRequestRepository.Read();
        //    IQueryable<PermitRequestViewModel> permitRequests = JsonSerializer.Deserialize<List<PermitRequestViewModel>>(result).AsQueryable();
        //    _permitRequestRepository.DisposeDBObjects();
        //    DataSourceResult dsResult = permitRequests.ToDataSourceResult(request);
        //    return Json(dsResult);
        //}

        public async Task<IActionResult> Read([DataSourceRequest] DataSourceRequest request)
        {
            string result = _permitRequestRepository.Read();
            IQueryable<PermitRequestViewModel> permitRequests = JsonSerializer.Deserialize<List<PermitRequestViewModel>>(result).AsQueryable();
            _permitRequestRepository.DisposeDBObjects();

            // Filter requests based on the current user's role and username
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            string currentUserRole = _userManager.GetRolesAsync(currentUser).Result[0];
            if (currentUserRole == "OWNER" || currentUserRole == "CONSULTANT")
            {
                permitRequests = permitRequests.Where(x => x.UserId == currentUser.Id);
            }
            DataSourceResult dsResult = permitRequests.ToDataSourceResult(request);
            return Json(dsResult);
        }
    }
}

AccessManagementLaredo_App/Views/PermitRequest/Index.cshtml
@using AccessManagementLaredo_App.Models;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> userManager;

@{
    var currentUser = await userManager.GetUserAsync(User);
    var roles = userManager.GetRolesAsync(currentUser).Result;
    string currentUserRole = roles[0];
    string currentUserType = "";
    if (currentUserRole == "TRAFFIC" || currentUserRole == "TPD" || currentUserRole == "AREAOFFICE" || currentUserRole == "SUPERADMIN")
        currentUserType = "INTERNAL";
    else
        currentUserType = "EXTERNAL";
}

@* Page header *******************************************************************************************************************************@
<br />
<h1>
    Permit Requests Dashboard
</h1>
<br />

@* Button to create a new request ***************************************************************************************************************@
@{
    if (currentUserType == "EXTERNAL")
    {
                    <form method="get" asp-action="Index" asp-controller="NewRequest">
                        <kendo-button type="submit" id="newRequestButton" theme-color="ThemeColor.Primary" size="ComponentSize.Large">&nbsp;&nbsp;&nbsp; New Request &nbsp;&nbsp;&nbsp;</kendo-button>
                    </form>
                    <br />
    }
}

@* Block for Grid *******************************************************************************************************************************@
<kendo-grid name="permitRequestsGrid" on-data-bound="onWorkOrderDataBound" height="720">
    <datasource type="DataSourceTagHelperType.Ajax" page-size="20" server-operation="true" >
        <transport>
            <read url="/PermitRequest/Read" />
            <destroy url="/PermitRequest/Delete" />
        </transport>
        <schema>
            <model id="Id">
                <fields>
                    <field name="Id" type="number" editable="false"></field>
                    <field name="UserId" type="String" editable="false"></field>
                    <field name="PermitRequestNumber" type="String"></field>
                    <field name="RequestType" type="String" editable="false"></field>
                    <field name="RequestorFullName" type="String" editable="false"></field>
                    <field name="DateCreated" type="Date" editable="false"></field>
                    <field name="DateUpdated" type="Date" editable="false"></field>
                    <field name="StatusAreaOfficeCode" type="String" editable="false"></field>
                    <field name="StatusTrafficCode" type="String" editable="false"></field>
                    <field name="StatusTPDCode" type="String" editable="false"></field>
                    <field name="StatusExternalCode" type="String" editable="false"></field>

                    <field name="StatusAreaOfficeName" type="String" editable="false"></field>
                    <field name="StatusTrafficName" type="String" editable="false"></field>
                    <field name="StatusTPDName" type="String" editable="false"></field>
                    <field name="StatusExternalName" type="String" editable="false"></field>
                </fields>
            </model>
        </schema>
    </datasource>
    @* <editable mode="popup" template-id="popup-editor" /> *@
    <groupable enabled="true" />
    <sortable enabled="true" />
    <filterable enabled="true" />
    <pageable button-count="5" refresh="true" page-sizes="new int[] { 5, 10, 20 }">
    </pageable>
    <columns>
        <column field="Id" title="Id" hidden=true />
        @* <column field="Number" template="#=template(data)#" title="Request Id" width="150" /> *@
        <column field="PermitRequestNumber" title="Request #" width="120" />
        <column field="UserId" title="User Id" hidden=true />
        <column field="RequestType" title="Request" width="120" />
        <column field="RequestorFullName" title="Requestor Name" width="220" />
        <column field="DateCreated" title="Created on" format="{0:yyyy/MM/dd}" hidden=true width="170" />
        <column field="DateUpdated" title="Last Updated" format="{0:yyyy/MM/dd}" width="140" />
        @{
            if (currentUserType == "INTERNAL")
            {
                <column field="StatusAreaOfficeName" title="Status Area Office" />
                <column field="StatusTrafficName" title="Status Traffic" />
                <column field="StatusTPDName" title="Status TPD" />
            }
            else
            {
                <column field="StatusExternalName" title="Status" />
            }
        }
        <column width="135">
            <commands>
                <column-command text="Edit" click="editRecord"></column-command>
                <column-command text="Log" click="viewEventLog"></column-command>
            </commands>
        </column>
    </columns>
</kendo-grid>

@* Partial view for events log ********************************************************************************************************* *@
<partial name="_EventsLog" />

@* ************************************************************************************************************************************************************ *@
@*                                                                      Javascript code                                                                         *@
@* ************************************************************************************************************************************************************ *@
<script>
    function editRecord(e) {
        // Prevent the default edit behavior
        e.preventDefault();

        // Get the dataItem associated with the clicked button
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));

        // Get the ID of the selected record
        var id = dataItem.Id;
        var reqType = dataItem.RequestType;

        // Redirect to the new view with the record ID
        if ("@currentUserType" == "INTERNAL") {
            window.location.href = '@Url.Action("PermitRequestReview", "NewRequest")' + '?id=' + id + '&type=' + reqType;
        } else { 
            window.location.href = '@Url.Action("Index", "NewRequest")' + '?id=' + id + '&type=' + reqType;
        }
    }


    // Function to handle the Grid button click
    function viewEventLog(e) {
        // Get the grid instance
        var grid = $("#permitRequestsGrid").data("kendoGrid");

        // Get the clicked row's data item
        var dataItem = grid.dataItem($(e.currentTarget).closest("tr"));

        // Extract the ID or other necessary information from the row
        var id = dataItem.Id; 

        // Call the reusable function
        openEventsWindow('@currentUserRole', id);
    }

    function onWorkOrderDataBound(e) {
        var grid = this;
        grid.table.find("tr").each(function () {
            var dataItem = grid.dataItem(this);

            // Apply status styling to columns 7, 8, and 9
            [7, 8, 9].forEach(function (colIndex) {
                var cell = this.cells.item(colIndex);
                if (!cell) return;

                var statusText = cell.innerText.trim();
                var cssClass = "";

                switch (statusText) {
                    case "DRAFT":
                        cssClass = "status-css-draft";
                        break;
                    case "UNDER REVIEW":
                        cssClass = "status-css-under-review";
                        break;
                    case "AWAITING ACTION":
                        cssClass = "status-css-awaiting";
                        break;
                    case "RETURNED TO USER":
                        cssClass = "status-css-returned";
                        break;
                    case "APPROVED":
                    case "REVIEWED":
                    case "N/A":
                        cssClass = "status-css-approved";
                        break;
                    case "COMPLETE":
                        cssClass = "status-css-complete";
                        break;
                }

                if (cssClass) {
                    cell.innerHTML = `<span class="${cssClass}">${statusText}</span>`;
                }
            }, this); // bind `this` to the row context

            // Disable edit button logic
            var status7 = this.cells.item(7)?.innerText.trim();
            if ("@currentUserType" == "EXTERNAL") {
                if (status7 === "UNDER REVIEW" || status7 === "APPROVED") {
                    this.cells.item(8).getElementsByClassName("k-grid-Edit")[0].setAttribute("disabled", true);
                }
            } else {
                if (status7 === "RETURNED TO USER") {
                    this.cells.item(10).getElementsByClassName("k-grid-Edit")[0].setAttribute("disabled", true);
                }
            }

            kendo.bind($(this), dataItem);
        });
    }
</script>

<script id="events-template" type="text/x-kendo-template">

</script>